#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgpiod
Version  : 0.3
Release  : 3
URL      : https://github.com/brgl/libgpiod/archive/v0.3.tar.gz
Source0  : https://github.com/brgl/libgpiod/archive/v0.3.tar.gz
Summary  : C library and tools for interacting with the linux GPIO character device
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgpiod-bin = %{version}-%{release}
Requires: libgpiod-lib = %{version}-%{release}
Requires: libgpiod-license = %{version}-%{release}
BuildRequires : pkgconfig(libkmod)
BuildRequires : pkgconfig(libudev)

%description
libgpiod
========
libgpiod - C library and tools for interacting with the linux GPIO
character device (gpiod stands for GPIO device)

%package bin
Summary: bin components for the libgpiod package.
Group: Binaries
Requires: libgpiod-license = %{version}-%{release}

%description bin
bin components for the libgpiod package.


%package dev
Summary: dev components for the libgpiod package.
Group: Development
Requires: libgpiod-lib = %{version}-%{release}
Requires: libgpiod-bin = %{version}-%{release}
Provides: libgpiod-devel = %{version}-%{release}
Requires: libgpiod = %{version}-%{release}

%description dev
dev components for the libgpiod package.


%package lib
Summary: lib components for the libgpiod package.
Group: Libraries
Requires: libgpiod-license = %{version}-%{release}

%description lib
lib components for the libgpiod package.


%package license
Summary: license components for the libgpiod package.
Group: Default

%description license
license components for the libgpiod package.


%prep
%setup -q -n libgpiod-0.3
cd %{_builddir}/libgpiod-0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604898519
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604898519
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libgpiod
cp %{_builddir}/libgpiod-0.3/COPYING %{buildroot}/usr/share/package-licenses/libgpiod/2c378b484c6da96db8f05f9bd795fcf5ddad0205
%make_install
## install_append content
make -C src/tools
make -C src/tools install DESTDIR=%{buildroot}
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gpiodetect
/usr/bin/gpiofind
/usr/bin/gpioget
/usr/bin/gpioinfo
/usr/bin/gpiomon
/usr/bin/gpioset

%files dev
%defattr(-,root,root,-)
/usr/include/gpiod.h
/usr/lib64/libgpiod.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgpiod.so.0
/usr/lib64/libgpiod.so.0.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgpiod/2c378b484c6da96db8f05f9bd795fcf5ddad0205
