#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgpiod
Version  : 0.3
Release  : 1
URL      : https://github.com/brgl/libgpiod/archive/v0.3.tar.gz
Source0  : https://github.com/brgl/libgpiod/archive/v0.3.tar.gz
Summary  : C library and tools for interacting with the linux GPIO character device
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgpiod-lib = %{version}-%{release}
Requires: libgpiod-license = %{version}-%{release}
BuildRequires : pkgconfig(libkmod)
BuildRequires : pkgconfig(libudev)

%description
libgpiod
========
libgpiod - C library and tools for interacting with the linux GPIO
character device (gpiod stands for GPIO device)

%package dev
Summary: dev components for the libgpiod package.
Group: Development
Requires: libgpiod-lib = %{version}-%{release}
Provides: libgpiod-devel = %{version}-%{release}
Requires: libgpiod = %{version}-%{release}
Requires: libgpiod = %{version}-%{release}

%description dev
dev components for the libgpiod package.


%package lib
Summary: lib components for the libgpiod package.
Group: Libraries
Requires: libgpiod-license = %{version}-%{release}

%description lib
lib components for the libgpiod package.


%package license
Summary: license components for the libgpiod package.
Group: Default

%description license
license components for the libgpiod package.


%prep
%setup -q -n libgpiod-0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564258597
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1564258597
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libgpiod
cp COPYING %{buildroot}/usr/share/package-licenses/libgpiod/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libgpiod.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgpiod.so.0
/usr/lib64/libgpiod.so.0.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgpiod/COPYING
